### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isPathIgnored' of null

### ISSUE THREAD

**Issue by malexandre** [suda/yuno-commit#4]
It occurs when we save a file in a non-git project. I'm just starting a new project, I didn't make the git init for now, and I can't save because of this bug.

**Atom Version**: 0.180.0
**System**: linux 3.18.3-201.fc21.x86_64
**Thrown From**: [yuno-commit](https://github.com/suda/yuno-commit) package, v0.0.2

### Stack Trace

Uncaught TypeError: Cannot read property 'isPathIgnored' of null

```
At /home/marc/git/dotfiles/.atom/packages/yuno-commit/lib/yuno-commit-view.coffee:55

TypeError: Cannot read property 'isPathIgnored' of null
  at YunoCommitView.module.exports.YunoCommitView.walkPath (/home/marc/git/dotfiles/.atom/packages/yuno-commit/lib/yuno-commit-view.coffee:55:55)
  at atom-workspace.<anonymous> (/home/marc/git/dotfiles/.atom/packages/yuno-commit/lib/yuno-commit-view.coffee:24:9)
  at atom-workspace.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app/src/window-event-handler.js:176:20)

```

### Commands

```
     -4:45.6 tree-view:move (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -4:43.9 core:move-right (atom-text-editor.editor.mini)
     -4:43.2 core:backspace (atom-text-editor.editor.mini)
     -4:41.6 core:confirm (atom-text-editor.editor.mini)
     -2:36.9 application:open-folder (atom-text-editor.editor)
     -2:09.3 tree-view:paste (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:05.1 tree-view:remove (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -2:01.0 tree-view:move (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:58.5 core:move-right (atom-text-editor.editor.mini)
     -1:58.2 core:backspace (atom-text-editor.editor.mini)
     -1:58.0 core:confirm (atom-text-editor.editor.mini)
     -1:09.2 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:09.2 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -1:09.2 editor:newline (atom-text-editor.editor.is-focused)
     -1:06.5 core:backspace (atom-text-editor.editor.is-focused)
  2x -1:05.1 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      ".git",
      "node_modules",
      ".sass-cache",
      "bower_components",
      "*.pyc",
      "blobstore",
      "build-tmp",
      ".search_index",
      "datastore"
    ],
    "disabledPackages": [
      "welcome",
      "timecop",
      "styleguide",
      "release-notes",
      "language-toml",
      "highlight-line",
      "linter-pylint",
      "file-type-icons"
    ],
    "themes": [
      "isotope-ui",
      "material"
    ],
    "projectHome": "/home/marc/git",
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.2.3
angularjs, v0.1.0
atom-beautify, v0.21.3
atom-color-highlight, v3.0.8
autoclose-html, v0.15.0
autocomplete-paths, v1.0.2
autocomplete-plus, v2.1.6
autocomplete-snippets, v1.0.1
color-picker, v1.4.4
docblockr, v0.5.8
emmet, v2.3.3
file-icons, v1.4.11
git-log, v0.2.0
hex, v0.5.0
highlight-selected, v0.9.0
isotope-ui, v1.5.0
linter, v0.11.1
linter-csslint, v0.0.11
linter-jshint, v0.1.0
linter-scss-lint, v0.0.11
material, v1.0.0
minimap, v4.2.2
minimap-highlight-selected, v4.0.0
pretty-json, v0.3.2
project-manager, v1.15.5
react, v0.9.9
regex-railroad-diagram, v0.6.3
sassbeautify, v0.2.0
subword-navigation, v2.3.0
tabs-to-spaces, v0.8.1
terminal-panel, v1.9.2
yuno-commit, v0.0.2
```

**Comment by MoOx** [comment]
Same issue over there. I am saving a file, but I cannot.

**Comment by MoOx** [comment]
Note that the folder doesn't have a .git folder, maybe that's causing the issue.

**Comment by suda** [comment]
Can you encounter this issue with latest (0.3.1) version?
